#!/usr/bin/env bash
if [ -z "$1" ]
  then
    docker-compose exec --user www-data webserver grunt exec
    docker-compose exec --user www-data webserver grunt less
    docker-compose exec --user www-data webserver grunt deploy
    docker-compose exec --user www-data webserver grunt watch
else
    docker-compose exec --user www-data webserver grunt exec:$@
    docker-compose exec --user www-data webserver grunt less:$@
    docker-compose exec --user www-data webserver grunt watch:$@
fi
